#!/usr/bin/env bash
# bootstrap.sh — one-shot environment setup for the copilot orchestration system.
# Idempotent: safe to re-run; existing config.yaml is never overwritten.
#
# Testability hooks (env vars):
#   BOOTSTRAP_NO_VENV=1           skip venv creation and pip install
#   BOOTSTRAP_NO_SCAN=1           skip codegraph.py scan
#   BOOTSTRAP_PROFILE_OVERRIDE=X  force a specific profile (tiny|small|medium|large|xlarge)
#   REPO_ROOT=/path               override repo root detection

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "${REPO_ROOT:-}" ]; then
    REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || dirname "$(dirname "$SCRIPT_DIR")")"
fi

CACHE="$REPO_ROOT/.github/.cache"
CONFIG="$REPO_ROOT/.github/config.yaml"
TOOLS="$REPO_ROOT/.github/tools"
VENV="$CACHE/.venv"

# ---------------------------------------------------------------------------
# Profile detection
# ---------------------------------------------------------------------------
if [ -n "${BOOTSTRAP_PROFILE_OVERRIDE:-}" ]; then
    profile="$BOOTSTRAP_PROFILE_OVERRIDE"
    files=0
    loc=0
else
    if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
        files=$(git -C "$REPO_ROOT" ls-files 2>/dev/null | wc -l | tr -d ' ')
        loc_raw=$(cd "$REPO_ROOT" && git ls-files 2>/dev/null \
                  | xargs -r wc -l 2>/dev/null | tail -n1 | awk '{print $1}')
    else
        files=$(find "$REPO_ROOT" -type f \
                    ! -path '*/.git/*' \
                    ! -path '*/.github/.cache/*' \
                    ! -path '*/node_modules/*' \
                    ! -path '*/.venv/*' \
                    ! -path '*/dist/*' \
                    ! -path '*/build/*' \
                    | wc -l | tr -d ' ')
        loc_raw=0
    fi
    loc="${loc_raw:-0}"
    files="${files:-0}"

    # Replicate config.py resolve_profile thresholds:
    #   both files AND loc must fit; whichever dimension exceeds escalates.
    profile="xlarge"
    for tier in tiny small medium large; do
        case "$tier" in
            tiny)   mf=50;    ml=2000    ;;
            small)  mf=500;   ml=20000   ;;
            medium) mf=5000;  ml=200000  ;;
            large)  mf=50000; ml=2000000 ;;
        esac
        if [ "$files" -le "$mf" ] && [ "$loc" -le "$ml" ]; then
            profile="$tier"
            break
        fi
    done
fi

# ---------------------------------------------------------------------------
# Directory structure
# ---------------------------------------------------------------------------
mkdir -p \
    "$CACHE/memory/decisions" \
    "$CACHE/memory/sessions" \
    "$CACHE/logs"

# ---------------------------------------------------------------------------
# Cache .gitignore — exclude everything under .cache from git
# ---------------------------------------------------------------------------
if [ ! -f "$CACHE/.gitignore" ]; then
    printf '*\n!.gitignore\n' > "$CACHE/.gitignore"
fi

# ---------------------------------------------------------------------------
# Write config.yaml (only if not present — never overwrite user edits).
# Exception: if profile is still 'auto', replace it with the detected value
# so Python tools get an actual profile, not a vague default.
# ---------------------------------------------------------------------------
if [ -f "$CONFIG" ] && grep -q "^profile: auto" "$CONFIG"; then
    sed -i "s/^profile: auto$/profile: $profile/" "$CONFIG"
fi
if [ ! -f "$CONFIG" ]; then
    cat > "$CONFIG" << YAML
# Auto-generated by bootstrap.sh. Safe to edit; re-running will not overwrite.
profile: $profile
profile_thresholds:
  tiny:   { max_files: 50,    max_loc: 2000    }
  small:  { max_files: 500,   max_loc: 20000   }
  medium: { max_files: 5000,  max_loc: 200000  }
  large:  { max_files: 50000, max_loc: 2000000 }
features:
  code_graph: auto
  memory_compaction: auto
  multi_agent: auto
  worktree_isolation: auto
  validator_gate: auto
codegraph:
  exclude:
    - "**/node_modules/**"
    - "**/.venv/**"
    - "**/.github/.cache/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/target/**"
    - "**/.git/**"
    - "**/vendor/**"
  languages:
    tier1: [python, javascript, typescript, tsx, go, java, rust, c, cpp]
    tier2: []
  budgets:
    envelope_default_tokens: 2000
    impact_max_depth: 3
  scan:
    workers: auto
    batch_size: 5000
memory:
  budgets:
    checkpoint: { soft: 2000, hard: 4000  }
    sessions:   { soft: 8000, hard: 16000 }
    learnings:  { soft: 4000, hard: 8000  }
    glossary:   { soft: 4000, hard: 8000  }
  compaction_model: claude-sonnet-4-6
  archive_after_days: 7
dispatch: {}
models:
  fast:     claude-haiku-4-5
  standard: claude-sonnet-4-6
  thinking: claude-opus-4-6
routing: {}
YAML
fi

# ---------------------------------------------------------------------------
# Placeholder memory files (only if not present)
# ---------------------------------------------------------------------------
if [ ! -f "$CACHE/memory/checkpoint.md" ]; then
    printf '# Checkpoint\n\n_Initial bootstrap. No sessions recorded yet._\n' \
        > "$CACHE/memory/checkpoint.md"
fi
if [ ! -f "$CACHE/memory/learnings.md" ]; then
    printf '# Learnings\n\n' > "$CACHE/memory/learnings.md"
fi
if [ ! -f "$CACHE/memory/glossary.md" ]; then
    printf '# Glossary\n\n' > "$CACHE/memory/glossary.md"
fi

# ---------------------------------------------------------------------------
# Placeholder project-context.md (updated later by @scribe via /init)
# ---------------------------------------------------------------------------
if [ ! -f "$CACHE/project-context.md" ]; then
    cat > "$CACHE/project-context.md" << 'MD'
# Project Context

> Auto-generated by bootstrap.sh. Update by running `/init` in Copilot Chat
> (triggers @scribe to analyze and rewrite this file).

## Tech Stack
_Not yet analyzed — run `/init` to populate._

## Architecture
_Not yet analyzed._

## Entry Points
_Not yet analyzed._

## Testing
_Not yet analyzed._

## Build Commands
_Not yet analyzed._

## Recent Structural Changes
_None recorded yet._
MD
fi

# ---------------------------------------------------------------------------
# Python venv + deps (skip for tiny or BOOTSTRAP_NO_VENV=1)
# ---------------------------------------------------------------------------
if [ "$profile" != "tiny" ] && [ "${BOOTSTRAP_NO_VENV:-0}" != "1" ]; then
    if [ ! -d "$VENV" ]; then
        echo "Creating Python venv at $VENV ..."
        python3 -m venv "$VENV"
    fi
    echo "Installing Python dependencies ..."
    "$VENV/bin/pip" install --quiet --upgrade pip
    "$VENV/bin/pip" install --quiet -r "$TOOLS/requirements.txt"
fi

# ---------------------------------------------------------------------------
# Code graph scan (skip for tiny or BOOTSTRAP_NO_SCAN=1)
# ---------------------------------------------------------------------------
if [ "$profile" != "tiny" ] && [ "${BOOTSTRAP_NO_SCAN:-0}" != "1" ]; then
    if [ "${BOOTSTRAP_NO_VENV:-0}" = "1" ]; then
        PYTHON_BIN="$(command -v python3)"
    else
        PYTHON_BIN="$VENV/bin/python"
    fi
    DB="$CACHE/codegraph.db"
    echo "Running code graph scan ..."
    "$PYTHON_BIN" "$TOOLS/codegraph.py" scan \
        --root "$REPO_ROOT" \
        --db "$DB" \
        --exclude \
            "**/node_modules/**" \
            "**/.venv/**" \
            "**/.github/.cache/**" \
            "**/dist/**" \
            "**/build/**" \
            "**/target/**" \
            "**/.git/**" \
            "**/vendor/**"
    # Write human-readable summary
    "$PYTHON_BIN" "$TOOLS/codegraph.py" stats \
        --db "$DB" --json > "$CACHE/codegraph.json" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
printf '\nbootstrap complete\n'
printf '  profile: %s\n' "$profile"
printf '  files:   %s\n' "${files:-n/a}"
printf '  loc:     %s\n' "${loc:-n/a}"
printf '  cache:   %s\n' "$CACHE"
printf '\n'
if [ "$profile" = "tiny" ]; then
    printf 'tiny profile: code graph disabled. Agents use grep/find directly.\n'
else
    printf "Next: run '/init' in Copilot Chat to have @scribe update project-context.md.\n"
fi
